#!/usr/bin/python2.7

import sys
import subprocess
import os

#exec node $dn/src/jsflow.js $*

bn=os.path.dirname(sys.argv[0])

subprocess.call(['node',bn+'/out/Toplevel/nodejs/NodeFlow.js','--observable']+sys.argv[1:])
